server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name pch.alektasolutions.com;

    ssl_certificate /etc/letsencrypt/live/pch.alektasolutions.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pch.alektasolutions.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 20M;

    include /var/www/pinaka-commerce-hub/nginx/api-locations.conf;

    # React frontend. Keep this last so API requests are not handled by the SPA fallback.
    location / {
        root /var/www/pdh;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name pch.alektasolutions.com;
    return 301 https://$host$request_uri;
}
