import { IsEmpty, IsEnum, IsOptional, IsString, MaxLength } from 'class-validator';
import { StoreTypeStatus } from '../../../entities/store-type.entity';

export class CreateStoreTypeDto {
  @IsEmpty({ message: 'storeTypeCode is generated by the database and must not be supplied' })
  storeTypeCode!: string;

  @IsString()
  @MaxLength(100)
  name!: string;

  @IsOptional()
  @IsString()
  description?: string;

  @IsOptional()
  @IsEnum(StoreTypeStatus)
  status?: StoreTypeStatus;
}

export class UpdateStoreTypeDto {
  @IsEmpty({ message: 'storeTypeCode is generated by the database and cannot be changed' })
  storeTypeCode?: string;

  @IsOptional()
  @IsString()
  @MaxLength(100)
  name?: string;

  @IsOptional()
  @IsString()
  description?: string;

  @IsOptional()
  @IsEnum(StoreTypeStatus)
  status?: StoreTypeStatus;
}
