-- PostgreSQL schema for the React merchant onboarding wizard.
-- Apply to the configured application database with node scripts/setup-merchant-db.cjs.

CREATE TABLE IF NOT EXISTS merchants (
  id VARCHAR(100) PRIMARY KEY,
  "businessName" VARCHAR(255) NOT NULL,
  "legalBusinessName" VARCHAR(255),
  "businessType" VARCHAR(50) NOT NULL DEFAULT 'RETAIL',
  "retailSubCategory" VARCHAR(50),
  "ownerName" VARCHAR(150) NOT NULL,
  "firstName" VARCHAR(100), "lastName" VARCHAR(100),
  email VARCHAR(255) UNIQUE NOT NULL, phone VARCHAR(50) NOT NULL,
  "alternatePhone" VARCHAR(50), "jobTitle" VARCHAR(150),
  "billingContact" BOOLEAN NOT NULL DEFAULT TRUE, "taxId" VARCHAR(100),
  country VARCHAR(100), state VARCHAR(100), city VARCHAR(100), "postalCode" VARCHAR(30),
  "businessAddress" TEXT, "kycStatus" VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  "kycDocuments" JSONB NOT NULL DEFAULT '[]'::jsonb,
  status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  "onboardingStep" VARCHAR(50) NOT NULL DEFAULT 'STEP1_BUSINESS',
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stores (
  id VARCHAR(100) PRIMARY KEY,
  "merchantId" VARCHAR(100) NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
  "storeName" VARCHAR(255) NOT NULL, "storeCode" VARCHAR(50) UNIQUE NOT NULL,
  "storeType" VARCHAR(50) NOT NULL DEFAULT 'RETAIL', "baseUrl" VARCHAR(2048), address JSONB NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'USD', timezone VARCHAR(100) NOT NULL DEFAULT 'UTC',
  "taxRate" DECIMAL(5,2) NOT NULL DEFAULT 8.25, "activationPin" VARCHAR(10) NOT NULL,
  "autoAcceptOrders" BOOLEAN NOT NULL DEFAULT TRUE, status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
  "operationalStatus" VARCHAR(50) NOT NULL DEFAULT 'OPEN', channels JSONB NOT NULL DEFAULT '[]'::jsonb,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id VARCHAR(100) PRIMARY KEY,
  "merchantId" VARCHAR(100) UNIQUE NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
  "planCode" VARCHAR(50) NOT NULL DEFAULT 'PRO', "planName" VARCHAR(100) NOT NULL,
  "maxStoresAllowed" INTEGER NOT NULL DEFAULT 3, entitlements JSONB NOT NULL DEFAULT '[]'::jsonb,
  "billingCycle" VARCHAR(20) NOT NULL DEFAULT 'MONTHLY', "trialDays" INTEGER NOT NULL DEFAULT 0,
  price DECIMAL(10,2) NOT NULL DEFAULT 99.00, status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
  "currentPeriodStart" TIMESTAMPTZ, "currentPeriodEnd" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS stores_merchant_id_idx ON stores ("merchantId");

-- Safe upgrades when the original Module 1 tables already exist.
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS "legalBusinessName" VARCHAR(255);
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS "firstName" VARCHAR(100);
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS "lastName" VARCHAR(100);
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS "alternatePhone" VARCHAR(50);
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS "jobTitle" VARCHAR(150);
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS "billingContact" BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS country VARCHAR(100);
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS state VARCHAR(100);
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS "postalCode" VARCHAR(30);
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS "businessAddress" TEXT;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS "baseUrl" VARCHAR(2048);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS "phone" VARCHAR(50);
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS "trialDays" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS "websiteConnector" JSONB;

CREATE TABLE IF NOT EXISTS onboarding_audit_logs (
  id VARCHAR(100) PRIMARY KEY,
  "merchantId" VARCHAR(100) NOT NULL,
  "storeId" VARCHAR(100),
  action VARCHAR(100) NOT NULL,
  "performedBy" VARCHAR(255) NOT NULL,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
